version: '3.3'
services:
  postgres:
    image: postgres:16.6-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_bot
    ports:
      - "15432:5432"

  devil-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
