services:
  devil-bot:
    image: $DOCKER_IMAGE_NAME
    env_file:
      - .env
    command: /bin/bash start.sh

  scheduler:
    image: $DOCKER_IMAGE_NAME
    command: python3 src/scheduler.py
    env_file:
      - .env
