version: '3.3'
services:
  devil-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./alembic.ini:/etc/app/alembic.ini
    env_file:
      - .env
    command: /bin/bash start.sh

  scheduler:
    build:
      dockerfile: Dockerfile
      context: .
    command: python3 src/scheduler.py
    env_file:
      - .env
    volumes:
      - ./:/app
