"""update_models

Revision ID: 2737c9e3048f
Revises: 83b560c54101
Create Date: 2025-02-20 11:46:31.822883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2737c9e3048f'
down_revision = '83b560c54101'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('clans', 'update_at')
    op.add_column('heroes_of_users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('heroes_of_users', 'update_at')
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('heroes_of_users', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('heroes_of_users', 'updated_at')
    op.add_column('clans', sa.Column('update_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('clans', 'updated_at')
    # ### end Alembic commands ###


def upgrade_read():
    pass


def downgrade_read():
    pass

