"""first migration

Revision ID: 5a46f5026091
Revises: 
Create Date: 2024-10-14 20:04:15.708173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a46f5026091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_events',
    sa.Column('name_event', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.UniqueConstraint('name_event')
    )
    op.create_table('clans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_clan', sa.String(), nullable=False),
    sa.Column('time_kz', sa.Integer(), server_default=sa.text('18'), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('news', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('start', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('description_of_the_kz', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('subscription_rock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('remain_zero_rock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clans_id'), 'clans', ['id'], unique=False)
    op.create_table('text_table',
    sa.Column('name_text', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name_text'),
    sa.UniqueConstraint('name_text')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=4), nullable=True),
    sa.Column('send_msg', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('heroes_of_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('clan_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('time_change_kz', sa.Integer(), server_default=sa.text('18'), nullable=False),
    sa.Column('time_collection_energy', sa.Integer(), server_default=sa.text('12'), nullable=False),
    sa.Column('subscription_rock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('subscription_energy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description_of_the_kz', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_of_users_id'), 'heroes_of_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_of_users_id'), table_name='heroes_of_users')
    op.drop_table('heroes_of_users')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('text_table')
    op.drop_index(op.f('ix_clans_id'), table_name='clans')
    op.drop_table('clans')
    op.drop_table('check_events')
    # ### end Alembic commands ###


def upgrade_read():
    pass


def downgrade_read():
    pass

