"""add_thread_id

Revision ID: e1c436349113
Revises: a06b6c3715d1
Create Date: 2025-08-11 10:44:39.713930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c436349113'
down_revision = 'a06b6c3715d1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('thread_id', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clans', 'thread_id')
    # ### end Alembic commands ###


def upgrade_read():
    pass


def downgrade_read():
    pass

