"""add_update_and_create_at

Revision ID: eaf7b0c20552
Revises: 0b00650b103a
Create Date: 2025-02-20 09:24:38.224540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaf7b0c20552'
down_revision = '0b00650b103a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_date',
       existing_type=postgresql.TIMESTAMP(),
       type_=sa.Date(),
       existing_nullable=False)
    op.add_column('heroes_of_users', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('heroes_of_users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('news', 'date_pub',
        existing_type=sa.VARCHAR(),
        type_=sa.DateTime(),
        existing_nullable=True,
        postgresql_using='date_pub::timestamp without time zone'
    )
    op.add_column('users', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_user_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade_write():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'update_at')
    op.alter_column('news', 'date_pub',
       existing_type=sa.DateTime(),
       type_=sa.VARCHAR(),
       existing_nullable=True)
    op.drop_column('heroes_of_users', 'created_at')
    op.drop_column('heroes_of_users', 'update_at')
    op.alter_column('events', 'event_date',
       existing_type=sa.Date(),
       type_=postgresql.TIMESTAMP(),
       existing_nullable=False)
    # ### end Alembic commands ###


def upgrade_read():
    pass


def downgrade_read():
    pass

